### ISSUE TITLE
Ask for confirmation when closing page

### ISSUE THREAD

**Issue by PoochieMix** [RileyCampbell73/Cubeventory#4]
I'd love to use this tool but I'm a bit wary of my players accidentally closing the page before they remember to save. Could it be updated to ask before they close the tab, in case they haven't saved? Or possibly some kind of auto-save.

**Comment by RileyCampbell73** [comment]
Hi,

You inventory should automatically save to local storage when leaving the page (via the "beforeunload" event). Can you confirm you're seeing this behavior?

**Comment by PoochieMix** [comment]
Oh boy, I didn't even know that was a functionality already. It works just like you say, thanks for pointing it out
